// Core OMS module: state machine, validation, cluster service, snapshot, FIX encoder.
dependencies {
    implementation project(':oms-codec')
    implementation libs.agrona
    implementation libs.aeron.client
    implementation libs.aeron.driver
    implementation libs.aeron.cluster
    implementation libs.aeron.archive
    implementation libs.slf4j.api
    runtimeOnly    libs.logback
}
